confirm_os_window_close 0
# Shell
shell zsh
# Font
font_family      JetBrainsMono Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size 12.0
# Window
window_padding_width 0
background_opacity 1.0
# Cursor
cursor_shape block
cursor_blink_interval 0
# Tabs
tab_bar_edge bottom
tab_bar_style powerline
tab_powerline_style slanted
# Misc
enable_audio_bell no
visual_bell_duration 0
copy_on_select yes
strip_trailing_spaces smart
sync_to_monitor yes
repaint_delay 10
input_delay 3
# BEGIN_KITTY_THEME
# Kanagawa
include kanagawa-paper.conf
# END_KITTY_THEME
