confirm_os_window_close 0

# Shell
shell zsh

# Font
font_family      JetBrainsMono Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size 12.0

# Window
window_padding_width 0
background_opacity 1.0

# Cursor
cursor_shape block
cursor_blink_interval 0

# Tabs
tab_bar_edge bottom
tab_bar_style powerline
tab_powerline_style slanted

# Misc
enable_audio_bell no
visual_bell_duration 0
copy_on_select yes
strip_trailing_spaces smart
sync_to_monitor yes
repaint_delay 10
input_delay 3

color0 #4e4539
color1 #ffb4ab
color2 #ffd799
color3 #dac3a3
color4 #d6e4a3
color5 #eac07e
color6 #dac3a3
color7 #e9e1d9
color8 #9a8f80
color9 #ffb4ab
color10 #ffd799
color11 #dac3a3
color12 #d6e4a3
color13 #eac07e
color14 #dac3a3
color15 #e9e1d9

cursor                #e9e1d9
cursor_text_color     #16130e
background            #16130e
foreground            #e9e1d9
selection_foreground  #d2c5b5
selection_background  #4e4539
active_border_color   #ffd799
inactive_border_color #4e4539
url_color             #ffd799

active_tab_foreground   #432c00
active_tab_background   #ffd799
inactive_tab_foreground #d2c5b5
inactive_tab_background #4e4539
cursor_trail_color      #d2c5b5

