confirm_os_window_close 0

# Shell
shell zsh

# Font
font_family      JetBrainsMono Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size 12.0

# Window
window_padding_width 0
background_opacity 1.0

# Cursor
cursor_shape block
cursor_blink_interval 0

# Tabs
tab_bar_edge bottom
tab_bar_style powerline
tab_powerline_style slanted

# Misc
enable_audio_bell no
visual_bell_duration 0
copy_on_select yes
strip_trailing_spaces smart
sync_to_monitor yes
repaint_delay 10
input_delay 3

# Colors
color0 #544247
color1 #ffb4ab
color2 #ffb0c8
color3 #f1b7c7
color4 #ffb783
color5 #ffb0c8
color6 #f1b7c7
color7 #efdee1
color8 #a18b90
color9 #ffb4ab
color10 #ffb0c8
color11 #f1b7c7
color12 #ffb783
color13 #ffb0c8
color14 #f1b7c7
color15 #efdee1

cursor                #efdee1
cursor_text_color     #191113
background            #191113
foreground            #efdee1
selection_foreground  #d9c0c6
selection_background  #544247
active_border_color   #ffb0c8
inactive_border_color #544247
url_color             #ffb0c8

active_tab_foreground   #5f0e33
active_tab_background   #ffb0c8
inactive_tab_foreground #d9c0c6
inactive_tab_background #544247
cursor_trail_color      #d9c0c6

