color0 #48454d
color1 #ffb4ab
color2 #ccc1e7
color3 #cac4d4
color4 #eab9cd
color5 #ccc1e7
color6 #cac4d4
color7 #e6e1e4
color8 #938f98
color9 #ffb4ab
color10 #ccc1e7
color11 #cac4d4
color12 #eab9cd
color13 #ccc1e7
color14 #cac4d4
color15 #e6e1e4

cursor                #e6e1e4
cursor_text_color     #141315
background            #141315
foreground            #e6e1e4
selection_foreground  #cac5ce
selection_background  #48454d
active_border_color   #ccc1e7
inactive_border_color #201f21
url_color             #ccc1e7

active_tab_foreground   #332c4a
active_tab_background   #ccc1e7
inactive_tab_foreground #cac5ce
inactive_tab_background #201f21
cursor_trail_color      #cac5ce

