shadowscolor = 0x000000ff
rootcolor = 0x141315ff
bordercolor = 0x64606bff
dropcolor = 0xccc1e780
splitcolor = 0xeab9cdff
focuscolor = 0xccc1e7ff
maximizescreencolor = 0xcac4d4ff
urgentcolor = 0xffb4abff
scratchpadcolor = 0xeab9cdff
globalcolor = 0x5c32c3ff
overlaycolor = 0x6a5096ff
jump_label_decorate_fg_color = 0xe6e1e4ff
jump_label_decorate_bg_color = 0x2a292cff
jump_label_decorate_focus_fg_color = 0x332c4aff
jump_label_decorate_focus_bg_color = 0xccc1e7ff
jump_label_decorate_border_color = 0x64606bff
group_bar_decorate_fg_color = 0xe6e1e4ff
group_bar_decorate_bg_color = 0x2a292cff
group_bar_decorate_focus_fg_color = 0x332c4aff
group_bar_decorate_focus_bg_color = 0xccc1e7ff
group_bar_decorate_border_color = 0x64606bff

